In [34]:
import pandas as pd
import numpy as np
from plotly import __version__
import matplotlib.pyplot as plt
import plotly.express as px

In [19]:
import cufflinks as cf

In [20]:
from plotly.offline import download_plotlyjs,init_notebook_mode,plot,iplot

In [21]:
import chart_studio.plotly as py

In [22]:
init_notebook_mode(connected=True)

In [23]:
cf.go_offline()

In [24]:
df = pd.DataFrame(np.random.randn(100,4), columns= 'A B C D'.split())

In [25]:
df.head()

          A         B         C         D
0 -0.293192  0.750635  0.627886 -0.020760
1  2.375309 -1.210284  0.381963  0.153791
2  0.393577  0.422559  0.624911 -0.955796
3  0.366751  0.268355 -1.412471  0.959378
4  0.812318 -2.015317  0.812774 -0.618718

In [26]:
df2 = pd.DataFrame({'Category':['A','B','C'],'Values':[32,43,50]})
df2.head()

  Category  Values
0        A      32
1        B      43
2        C      50

In [35]:
fig = px.line(df)
fig.show()

In [41]:
fig = px.scatter(df, x="A", y="B")
fig.show()

In [42]:
fig = px.bar(df2, x="Category", y="Values")
fig.show()

In [44]:
fig = px.bar(df.max())
fig.show()

In [ ]:
)