In [1]:
import pandas as pd
import numpy as np
from plotly import __version__
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
import cufflinks as cf

In [3]:
from plotly.offline import download_plotlyjs,init_notebook_mode,plot,iplot

In [4]:
import chart_studio.plotly as py

In [5]:
init_notebook_mode(connected=True)

In [6]:
cf.go_offline()

In [7]:
df = pd.DataFrame(np.random.randn(100,4), columns= 'A B C D'.split())

In [8]:
df.head()

          A         B         C         D
0 -1.387054  1.044103 -0.257759 -0.290473
1  0.896051 -0.561406 -1.788969 -2.788573
2  1.354042 -0.332338 -1.212941  0.627782
3 -1.294430 -0.809224  0.888935 -1.375512
4 -1.443663  0.248159 -0.563883 -0.847671

In [9]:
df2 = pd.DataFrame({'Category':['A','B','C'],'Values':[32,43,50]})
df2.head()

  Category  Values
0        A      32
1        B      43
2        C      50

In [10]:
fig = px.line(df)
fig.show()

In [11]:
fig = px.scatter(df, x="A", y="B")
fig.show()

In [12]:
fig = px.bar(df2, x="Category", y="Values")
fig.show()

In [13]:
fig = px.bar(df.max())
fig.show()

In [14]:
fig = px.box(df)
fig.show()

In [15]:
df3 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})

In [16]:
df3

   x   y  z
0  1  10  5
1  2  20  4
2  3  30  3
3  4  20  2
4  5  10  1

In [23]:
fig = px.histogram(df['A'], nbins = 50)
fig.show()

In [24]:
fig = px.histogram(df, nbins = 50)
fig.show()