In [4]:
import pandas as pd
import numpy as np
from plotly import __version__

In [6]:
import cufflinks as cf

In [7]:
from plotly.offline import download_plotlyjs,init_notebook_mode,plot,iplot

In [8]:
import chart_studio.plotly as py

In [9]:
init_notebook_mode(connected=True)

In [11]:
cf.go_offline()

In [12]:
df = pd.DataFrame(np.random.randn(100,4), columns= 'A B C D'.split())

In [14]:
df.head()

          A         B         C         D
0 -1.132331  2.093053  0.258234  0.834915
1 -0.033711  0.721007  0.348921  0.872698
2  1.299688 -0.153047  1.382919  0.328592
3  0.118870 -0.409134 -0.421324  0.656431
4  0.549840 -1.151353  0.081868  1.212087

In [15]:
df2 = pd.DataFrame({'Category':['A','B','C'],'Values':[32,43,50]})
df2.head()

  Category  Values
0        A      32
1        B      43
2        C      50